### ISSUE TITLE
Windows "pip install lenstools" fail

### ISSUE THREAD

**Issue by lxsyz** [apetri/LensTools#5]
After creating build "extern" directory:

`creating build\temp.win32-2.7\Release\lenstools\extern
    C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG /arch:SSE2 -Id:\lenstools\myproject\env\lib\site-packages\numpy-1.14.3-py2.7-win32.egg\numpy\core\include -Ie:\python\include -Id:\lenstools\myproject\env\PC -Id:\lenstools\myproject\env\lib\site-packages\numpy-1.14.3-py2.7-win32.egg\numpy\core\include -Ie:\python\include -Id:\lenstools\myproject\env\PC /Tclenstools\extern\_nbody.c /Fobuild\temp.win32-2.7\Release\lenstools\extern\_nbody.obj
    _nbody.c
    d:\lenstools\myproject\env\lib\site-packages\numpy-1.14.3-py2.7-win32.egg\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    c:\users\administrator\appdata\local\temp\pip-install-gqz5k5\lenstools\lenstools\extern\grid.h(10) : error C2054: expected '(' to follow 'inline'
    c:\users\administrator\appdata\local\temp\pip-install-gqz5k5\lenstools\lenstools\extern\grid.h(10) : error C2085: 'quadraticKernel' : not in formal parameter list
    c:\users\administrator\appdata\local\temp\pip-install-gqz5k5\lenstools\lenstools\extern\grid.h(10) : error C2143: syntax error : missing ';' before '{'
    lenstools\extern\_nbody.c(85) : error C2143: syntax error : missing ';' before 'type'
    lenstools\extern\_nbody.c(87) : error C2065: 'st' : undeclared identifier
    lenstools\extern\_nbody.c(87) : error C2223: left of '->error' must point to struct/union
    lenstools\extern\_nbody.c(88) : error C2065: 'st' : undeclared identifier
    lenstools\extern\_nbody.c(88) : error C2223: left of '->error' must point to struct/union
    lenstools\extern\_nbody.c(108) : error C2143: syntax error : missing '{' before '*'
    lenstools\extern\_nbody.c(108) : error C2371: '_apply_kernel2d' : redefinition; different basic types
            lenstools\extern\_nbody.c(27) : see declaration of '_apply_kernel2d'
    lenstools\extern\_nbody.c(121) : error C2275: 'PyObject' : illegal use of this type as an expression`

As you can see, the error is very  strange. Python version is 2.7, Windows version is 10, could you give me some advice?. Thank you very much!

**Comment by apetri** [comment]
Hi! I never tried to build on Windows, it could be a problem of the particular C compiler are you using; could you try to build with gcc (I believe the MinGW project is the one you are looking for)? I would advise you to build on UNIX though

**Comment by lxsyz** [comment]
Thank you, I have built it successfully on Linux.
