### ISSUE TITLE
CMB power spectrum in lenstools

### ISSUE THREAD

**Issue by orjuelajavier** [apetri/LensTools#6]
Hello, 
I have seen that there is a function in lensTools in which produce the power spectrum of the convergence map. So I would like to ask  if I can  use  that function in order to estimate the power spectrum of a CMB patch of 10x10dg^2; but in my case I have a numpy array of 224x224 which contains the temperature of the sky on that patch.
Thanks.

**Comment by apetri** [comment]
Hi! You most surely can 

import astropy.units as u
import lenstools as lt

t = lt.CMBTemperatureMap(data,angle=10*u.deg)

ell,power = t.powerSpectrum(ell_bins)

#returned ell are midpoints of ell_bins array

**Comment by orjuelajavier** [comment]
@apetri  Thank you very much!!!
