### ISSUE TITLE
Loading convergence map and calculating power spectrum

### ISSUE THREAD

**Issue by thunderflash314** [apetri/LensTools#7]
Hi, I'm trying to load a convergence map I have in .fits format, but I get the error "AttributeError: No ANGLE or SIDE keyword in header!" when I run 
conv_map = ConvergenceMap.load(map_filename)

I saved my convergence map in fits format using 

outfile = 'convergence_1.fits'
hdu = fits.PrimaryHDU(convergence)
hdu.writeto(outfile)

I would also be glad if you could tell me how exactly can one determine the parameter l_edges(the multipole bin edges) when trying to obtain the power spectrum.

Thanks for your help!

**Comment by apetri** [comment]
Hi, the default fits format loader assumes that there is a keyword ANGLE in the header which contains the side angle of the map in degrees. If there is no such keyword, an exception is thrown. You can the ANGLE key to the header upon saving OR you can instantiate the ConvergenceMap directly using its constructor ( ConvergenceMap(data,angle=<angle>*u.deg) ). 

l_edges are just the extremes of the multipole bins; in the output (l,Pl), l is the midpoint of the multipole bin ( len(l)==len(l_edges)-1 ) and Pl is the azimuthal average of the power spectrum over all the multipoles that fall in the same bin.

**Comment by thunderflash314** [comment]
Ah I see, Thanks a lot! I think I managed to make it work by entering the FOV angle into the fits header.

If you don't mind me asking you another question, I tried running the power spectrum generation example provided in the manual, with my convergence map as the input. When I set the value of the angle to 1 degree, I get an output for Pl that looks sensible. But, my actual value for the FOV angle is on the order of 5e-6 degrees, and when I try running the commands again, the output I get for Pl is just all zeros. Is there a limitation in the code for how small of an angle I can set for the fits? Or does this merely depend on the values set for l_edges?

**Comment by apetri** [comment]
You have to take into account that the FOV angle sets the minimum l that you can measure from the map. In flat sky approximation lmin ~ 2*pi/FOV which, with your FOV (are you sure the number is correct, it seems a really small FOV), is about 7e7... This means that, if all your l bins are centered around values which are much smaller than this lmin, you will get zeros as output.

**Comment by thunderflash314** [comment]
I see, yes the FOV is indeed very small, because I am trying to do simulations that involve high resolutions. My power spectrums have turned out to be singular spikes when I try to run the code, which is sort of what I expect.

I am still confused regarding the gaussian random field realization. To create a power spectrum, the input is the convergence map. Afterwards, to create the realization, the input is said power spectrum. Isn't it a bit circular? Since the goal of the realization is to obtain a convergence map. I feel I am misunderstanding something here.

**Comment by apetri** [comment]
You need to pass a ConvergenceMap to GaussianNoiseGenerator.forMap, that will tailor the noise realization to the fov/resolution of the input map. I understand this can be confusing. 

In alternative (better practice) instantiate the noise generator directly: gen = GaussianNoiseGenerator((512,512), 3.5*u.deg) 
This will instantiate a generator for a 3.5deg field of view with 512 pixels per side. Then use gen.fromConvPower

**Comment by thunderflash314** [comment]
Yes I tried instantiating the noise generator directly, as in the example. I am just a bit worried about the input power spectrum for gen.fromConvPower, because I made this using the convergence map initially. If I put it in simple terms, I start off with a smooth convergence map, and at the end after I use gen.fromConvPower, I end up with some gaussian noise added on top of this smooth map?

**Comment by apetri** [comment]
gen.fromConvPower will produce a random realization of an image, in real space, that has the same power spectrum as the input (of course, if you measure the power spectrum of the produced image, it won’t match the input exactly cause there was a random draw for the fourier coefficients involved). 

If you measure the input power from an existing map, gen.fromConvPower will give you a random realization of that power spectrum (of course all non-Gaussian effects will be erased)

If you supply a custom power spectrum (e.g. a flat shape for white noise), it will generate a map from that custom power spectrum. 

The generator does not add the generated map to the original one, you have to do that yourself (if your noise model is additive)

**Comment by thunderflash314** [comment]
Ah I see, I think I understand better now! Thanks :)
