### ISSUE TITLE
emcee function errors

### ISSUE THREAD

**Issue by knaidoo29** [apetri/LensTools#9]
Hi,

I installed this today and found some errors all related to calling functions from emcee. I'm using the latest version of emcee and I think they've changed some of the function names and file structure in their recent updates. Perhaps you could specify which version of emcee this is compatible with, so others don't run into similar issues, apologies if you have done this but I couldn't find it.

If you wanted to edit the code to work with the latest emcee I found the following edits removed these errors.

1. In _lenstools/utils/mpi.py_ I changed line 17:

`from emcee.utils import MPIPool` to `from emcee.mpi_pool import MPIPool`

2. in _lenstools/statistics/constraints.py_ and _lenstools/statistics/ensemble.py_ I changed the lines calling `from emcee.ensemble import _function_wrapper` to `from emcee.ensemble import _FunctionWrapper as _function_wrapper`

I've not tested any of the emcee related functions so I don't know if this breaks it elsewhere.

Best,

Krishna

**Comment by apetri** [comment]
Hi, in setup.py I included the compatible emcee version explicitly

https://github.com/apetri/LensTools/blob/master/setup.py#L306

does that not work?

**Comment by knaidoo29** [comment]
Ah, I didn't see that. 

For some reason my emcee says its version 0.0.0 which is not true... strange. So this is probably how it has gotten past the explicit version definition in your setup.py. In any case this doesn't seem to be an issue related to LensTools so I'll close the issue now. I hope the edits above are useful in future (if you plan to make it compatible with the latest emcee).

Thanks,

Krishna

**Comment by apetri** [comment]
Sure, thank you for the suggestions!
